<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\Libs\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="SkyHook.Unity">
      <HintPath>..\Libs\SkyHook.Unity.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\Libs\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\Libs\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager" />
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\Libs\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule" />
    <Reference Include="UnityEngine.UI">
      <HintPath>..\Libs\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>..\Libs\DOTween.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\Libs\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\Libs\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\Libs\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net" />
    <Reference Include="UnityEngine.Physics2DModule" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="RDTools">
      <HintPath>..\Libs\RDTools.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule" />
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\Libs\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="DOTweenPro">
      <HintPath>..\Libs\DOTweenPro.dll</HintPath>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="UnityEngine.AnimationModule" />
    <Reference Include="UnityEngine.SpriteMaskModule" />
    <Reference Include="Unity.Purchasing" />
    <Reference Include="Unity.Purchasing.SecurityStub" />
    <Reference Include="Unity.Purchasing.SecurityCore" />
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\Libs\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml" />
    <Reference Include="Rewired_Core" />
    <Reference Include="UnityEngine.PhysicsModule" />
    <Reference Include="UnityEngine.TextCoreFontEngineModule" />
    <Reference Include="System.Text.Json" />
    <Reference Include="Unity.Addressables" />
    <Reference Include="UnityFileDialog" />
    <Reference Include="UnityEngine.ImageConversionModule" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="UnityEngine.CrashReportingModule" />
    <Reference Include="UnityEngine.UnityAnalyticsModule" />
    <Reference Include="UnityEngine.UnityAnalyticsCommonModule" />
    <Reference Include="Rewired_Windows" />
    <Reference Include="System.Text.Encodings.Web" />
    <Reference Include="UnityEngine.UnityWebRequestAudioModule" />
    <Reference Include="UnityEngine.UnityWebRequestTextureModule" />
    <Reference Include="UnityEngine.ScreenCaptureModule" />
  </ItemGroup>
</Project>